ersion: '2'

services:
  influxdb:
    restart: always
    image: influxdb:1.8
    ports:
      - "8886:8086"
    volumes:
      - "./docker-speedtest-grafana/data/influxdb/:/var/lib/influxdb"
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=password"
      - "INFLUXDB_DB=speedtest"

  grafana:
    restart: always
    image: grafana/grafana:6.7.2
    volumes:
      - "./docker-speedtest-grafana/grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3030:3000"
    environment:
      - "GF_SERVER_ROOT_URL=http://localhost"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    depends_on:
      - influxdb

  speedtest:
    restart: always
    image: frdmn/speedtest-grafana:latest
    container_name: speedtest
    environment:
      - "SPEEDTEST_INTERVAL=1000"
      - "SPEEDTEST_HOST=local"
    depends_on:
      - influxdb